name: notes_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  get: ^4.6.5
  http: ^0.13.5
  onesignal_flutter: ^3.5.0
  google_fonts: ^3.0.1
  page_transition: ^2.0.9
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  flutter_inappwebview: ^5.7.2+3
  url_launcher: ^6.1.7
  fluttertoast: ^8.1.2
  cached_network_image: ^3.2.3
  lottie: ^2.1.0
  shimmer: ^2.0.0
  image_picker: ^0.8.6
  permission_handler: ^10.2.0
  custom_refresh_indicator: ^2.0.1
  local_auth: ^2.1.3
  firebase_auth: ^4.2.4
  firebase_core: ^2.4.1
  flutter_plugin_android_lifecycle: ^2.0.7
  google_sign_in: ^5.4.2
  change_app_package_name: ^1.1.0
  cloud_firestore: ^4.3.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
    - assets/svgs/