name: flutter_template
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  get: ^4.6.5
  http: ^0.13.5
  onesignal_flutter: ^3.4.1
  google_fonts: ^3.0.1
  page_transition: ^2.0.9
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  flutter_inappwebview: ^5.4.3+7
  url_launcher: ^6.1.5
  fluttertoast: ^8.0.9
  cached_network_image: ^3.2.2
  lottie: ^1.4.3
  shimmer: ^2.0.0
  image_picker: ^0.8.5+3
  permission_handler: ^10.1.0
#  dio: ^4.0.6
  custom_refresh_indicator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
    - assets/svgs/